/* 
 * Doctor Appointment API
 *
 * API for managing Doctor Appointment
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoctorAppointmentInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoctorAppointmentInputTests
    {
        // TODO uncomment below to declare an instance variable for DoctorAppointmentInput
        //private DoctorAppointmentInput instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoctorAppointmentInput
            //instance = new DoctorAppointmentInput();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoctorAppointmentInput
        /// </summary>
        [Test]
        public void DoctorAppointmentInputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoctorAppointmentInput
            //Assert.IsInstanceOfType<DoctorAppointmentInput> (instance, "variable 'instance' is a DoctorAppointmentInput");
        }


        /// <summary>
        /// Test the property 'Doctor'
        /// </summary>
        [Test]
        public void DoctorTest()
        {
            // TODO unit test for the property 'Doctor'
        }
        /// <summary>
        /// Test the property 'Patient'
        /// </summary>
        [Test]
        public void PatientTest()
        {
            // TODO unit test for the property 'Patient'
        }
        /// <summary>
        /// Test the property 'Dob'
        /// </summary>
        [Test]
        public void DobTest()
        {
            // TODO unit test for the property 'Dob'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
