/* 
 * Doctor Appointment API
 *
 * API for managing Doctor Appointment
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoctorAppointment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoctorAppointmentTests
    {
        // TODO uncomment below to declare an instance variable for DoctorAppointment
        //private DoctorAppointment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoctorAppointment
            //instance = new DoctorAppointment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoctorAppointment
        /// </summary>
        [Test]
        public void DoctorAppointmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoctorAppointment
            //Assert.IsInstanceOfType<DoctorAppointment> (instance, "variable 'instance' is a DoctorAppointment");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Doctor'
        /// </summary>
        [Test]
        public void DoctorTest()
        {
            // TODO unit test for the property 'Doctor'
        }
        /// <summary>
        /// Test the property 'Patient'
        /// </summary>
        [Test]
        public void PatientTest()
        {
            // TODO unit test for the property 'Patient'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Test]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
