/* 
 * Doctor Appointment API
 *
 * API for managing Doctor Appointment
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DoctorAppointmentList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DoctorAppointmentListTests
    {
        // TODO uncomment below to declare an instance variable for DoctorAppointmentList
        //private DoctorAppointmentList instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DoctorAppointmentList
            //instance = new DoctorAppointmentList();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DoctorAppointmentList
        /// </summary>
        [Test]
        public void DoctorAppointmentListInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DoctorAppointmentList
            //Assert.IsInstanceOfType<DoctorAppointmentList> (instance, "variable 'instance' is a DoctorAppointmentList");
        }



    }

}
